"""Generate fix.txt and airway.txt from the Navigraph DFD database.

These two files are what lets the API decide Mode S 1000 eligibility: field 15
is tokenised, airway tokens are expanded through airway.txt, and every
resulting point is looked up in fix.txt.

WHY fix.txt IS CLIPPED AND airway.txt IS NOT

fix.txt holds only the points INSIDE the Mode S area, so membership in fix.txt
IS the containment test -- the polygon is applied here, at build time, and the
server never runs point-in-polygon at runtime.

airway.txt keeps every airway chain that touches the area in FULL, including
the fixes outside it. That asymmetry is deliberate. An airway that leaves the
area and comes back would, if clipped, appear contiguous and a route using it
would wrongly qualify for 1000. Unclipped, the excursion survives as fixes that
airway.txt names but fix.txt does not contain, so expansion hits an
unresolvable point and fails closed to a discrete code.

Usage:  py tools/generate_navdata.py [--db db.s3db] [--area modes_area.geojson]
"""

from __future__ import annotations

import argparse
import json
import math
import sqlite3
from collections import defaultdict
from pathlib import Path

# Two consecutive legs further apart than this are not the same airway. The DFD
# reuses designators worldwide -- V3 exists in Europe, the USA and the Pacific --
# and the seqno counter does not always restart between them, so seqno alone
# leaves a single "airway" spanning lon -174..144. Measured over the whole
# database, real legs sit at p50 35 NM and p90 152 NM, and the histogram has a
# clear trough at 800-1000 NM before the continental jumps begin. 1000 NM cuts
# there, keeping genuine long oceanic legs.
MAX_LEG_NM = 1000.0


def great_circle_nm(lat1: float, lon1: float, lat2: float, lon2: float) -> float:
    p1, p2 = math.radians(lat1), math.radians(lat2)
    dl = math.radians(lon2 - lon1)
    cos_d = math.sin(p1) * math.sin(p2) + math.cos(p1) * math.cos(p2) * math.cos(dl)
    return 3440.065 * math.acos(max(-1.0, min(1.0, cos_d)))

FIX_HEADER = """\
# Mode S area fixes -- AIRAC {cycle}
#
# Generated by tools/generate_navdata.py from the Navigraph DFD database,
# clipped to modes_area.geojson. Do not edit by hand: re-run the generator.
#
# FORMAT   <ident> <latitude> <longitude>
#
# Signed decimal degrees. One line per unique identifier.
#
# Every fix listed here is INSIDE the Mode S conspicuity area. That is the
# whole point of the file: a route point present here is in the area, and a
# route point absent from here is either outside the area or unknown. Both
# cases deny code 1000, which is the conservative direction.
#
# ----------------------------------------------------------------------------
"""

AIRWAY_HEADER = """\
# Mode S area airways -- AIRAC {cycle}
#
# Maps an airway designator to its ordered fixes, so a field 15 token naming an
# airway can be expanded into the points it actually crosses.
#
# Generated by tools/generate_navdata.py from the Navigraph DFD database.
# Do not edit by hand: re-run the generator.
#
# FORMAT
#
#   AIRWAY <name>
#   <fix>
#   <fix>
#   ...
#
# A block runs from its AIRWAY header to the next one, or to end of file. Blank
# lines and # comments are ignored anywhere.
#
# A designator may appear in MORE THAN ONE block when the airway is published as
# disjoint segments. Expand using whichever block contains both the entry and
# the exit fix; a designator whose blocks contain neither pairing cannot be
# expanded and denies code 1000.
#
# NOT CLIPPED TO THE AREA
#
# Every airway with at least one fix inside the Mode S area appears here with
# its COMPLETE fix list, including fixes outside the area. This is deliberate.
# An airway that leaves the area and re-enters it would, if clipped, look like
# it never left, and a route flying it would wrongly qualify for code 1000.
# Listing the excursion means those fixes resolve against fix.txt and are not
# found, which correctly denies 1000.
#
# So: a fix named here but missing from fix.txt is OUTSIDE the area. That is
# information, not a data gap.
#
# ----------------------------------------------------------------------------
"""


PROCEDURE_HEADER = """\
# Mode S area SID/STAR designators -- AIRAC {cycle}
#
# Generated by tools/generate_navdata.py from the Navigraph DFD database, for
# every airport inside modes_area.geojson. Do not edit by hand: re-run the
# generator.
#
# FORMAT   <airport> <SID|STAR> <designator>
#
# WHY THIS FILE EXISTS
#
# A field 15 route names procedures as well as points:
#
#     N0450F350 ATREX5A ATREX UN871 LERGA ...
#
# ATREX5A is a SID, not a fix, so it is not in fix.txt. Without this file the
# tokeniser would treat it as an identifier that looks like a point but cannot
# be resolved, fail closed, and deny code 1000 to essentially every flight that
# files a SID -- which is nearly all of them.
#
# A token matching a designator published by the flight's OWN departure or
# destination aerodrome is a procedure name, and is skipped: the procedure's own
# path lies in that aerodrome's terminal area, which is inside the area by
# definition if the aerodrome is.
#
# MATCH ON THE AIRPORT, NOT THE DESIGNATOR ALONE
#
# Six designators worldwide are also real fix identifiers inside the area:
#
#     BRAVO  HON  NORTH  ROCIO  SOUTH  TSC
#
# Matching a bare designator against every airport's procedures would skip those
# six when they appear as genuine route points. Checking the token against the
# departure and destination aerodromes only -- which is all a field 15 procedure
# token can ever belong to -- removes the ambiguity entirely.
#
# ----------------------------------------------------------------------------
"""


class Area:
    """Union of the rings in a GeoJSON file; contains() means inside any ring."""

    def __init__(self, rings: list[list]) -> None:
        self.rings = rings
        lats = [pt[1] for r in rings for pt in r]
        lons = [pt[0] for r in rings for pt in r]
        self.bbox = (min(lats), min(lons), max(lats), max(lons))

    @classmethod
    def load(cls, path: Path) -> "Area":
        root = json.loads(path.read_text(encoding="utf-8"))
        rings: list[list] = []

        def walk(node):
            if not isinstance(node, dict):
                return
            kind = node.get("type")
            if kind == "FeatureCollection":
                for f in node.get("features") or []:
                    walk(f)
            elif kind == "Feature":
                walk(node.get("geometry"))
            elif kind == "Polygon":
                for ring in node.get("coordinates") or []:
                    if len(ring) >= 4:
                        rings.append(ring)
            elif kind == "MultiPolygon":
                for poly in node.get("coordinates") or []:
                    for ring in poly:
                        if len(ring) >= 4:
                            rings.append(ring)

        walk(root)
        if not rings:
            raise SystemExit(f"no polygon geometry in {path}")
        return cls(rings)

    @staticmethod
    def _in_ring(lat: float, lon: float, ring: list) -> bool:
        inside = False
        n = len(ring)
        for i in range(n):
            x1, y1 = ring[i][0], ring[i][1]
            x2, y2 = ring[(i + 1) % n][0], ring[(i + 1) % n][1]
            if (y1 > lat) != (y2 > lat):
                if lon < x1 + (lat - y1) * (x2 - x1) / (y2 - y1):
                    inside = not inside
        return inside

    def contains(self, lat, lon) -> bool:
        if lat is None or lon is None:
            return False
        south, west, north, east = self.bbox
        if not (south <= lat <= north and west <= lon <= east):
            return False
        return any(self._in_ring(lat, lon, r) for r in self.rings)


# Source tables for fix.txt, in precedence order: when one identifier is
# published by more than one table the first listed wins, so a VOR beats an
# enroute waypoint of the same name.
FIX_SOURCES = [
    ("VOR/DME", "select navaid_identifier, coalesce(navaid_latitude, dme_latitude),"
                " coalesce(navaid_longitude, dme_longitude) from tbl_d_vhfnavaids"),
    ("NDB", "select navaid_identifier, navaid_latitude, navaid_longitude"
            " from tbl_db_enroute_ndbnavaids"),
    ("WAYPOINT", "select waypoint_identifier, waypoint_latitude, waypoint_longitude"
                 " from tbl_ea_enroute_waypoints"),
]


def build_fixes(db: sqlite3.Connection, area: Area):
    """{ident: (lat, lon, section)} for every point inside the area."""
    fixes: dict[str, tuple[float, float, str]] = {}
    considered = 0
    collisions = 0
    for section, sql in FIX_SOURCES:
        for ident, lat, lon in db.execute(sql):
            if not ident or lat is None or lon is None:
                continue
            considered += 1
            if not area.contains(lat, lon):
                continue
            ident = ident.strip()
            if ident in fixes:
                # Same name, different point, both inside. Either resolves to
                # "inside", so eligibility is unaffected and the first wins.
                collisions += 1
                continue
            fixes[ident] = (lat, lon, section)
    return fixes, considered, collisions


def build_airways(db: sqlite3.Connection, area: Area):
    """[(name, [idents])] for every airway chain touching the area, unclipped.

    A designator is not unique worldwide, so it is split into chains wherever
    seqno stops increasing OR the next leg is further than MAX_LEG_NM away. Both
    tests are needed: the seqno counter does not reliably restart between the
    European V3 and the Pacific one, and without the distance test they fuse
    into a single airway wrapping most of the planet.

    Every chain touching the area is kept, so a designator published as disjoint
    segments yields more than one block under the same name.
    """
    by_name: dict[str, list[tuple]] = defaultdict(list)
    for name, seqno, ident, lat, lon in db.execute(
            "select route_identifier, seqno, waypoint_identifier, waypoint_latitude,"
            " waypoint_longitude from tbl_er_enroute_airways"
            " order by route_identifier, seqno"):
        by_name[name].append((seqno, ident, lat, lon))

    airways: list[tuple[str, list[str]]] = []
    outside_kept = 0
    multi_chain = 0
    for name in sorted(by_name):
        chains: list[list[tuple]] = [[]]
        previous: tuple | None = None
        for leg in by_name[name]:
            split = previous is not None and leg[0] <= previous[0]
            if not split and previous is not None and None not in (leg[2], leg[3],
                                                                   previous[2], previous[3]):
                split = great_circle_nm(previous[2], previous[3], leg[2], leg[3]) > MAX_LEG_NM
            if split:
                chains.append([])
            chains[-1].append(leg)
            previous = leg

        kept = [c for c in chains if any(area.contains(leg[2], leg[3]) for leg in c)]
        if len(kept) > 1:
            multi_chain += 1
        for chain in kept:
            idents: list[str] = []
            outside_here = 0
            for _, ident, lat, lon in chain:
                if not ident:
                    continue
                ident = ident.strip()
                if idents and idents[-1] == ident:
                    continue  # a hold or reversal over the same point
                idents.append(ident)
                if not area.contains(lat, lon):
                    outside_here += 1
            if len(idents) >= 2:
                airways.append((name.strip(), idents))
                outside_kept += outside_here
    return airways, outside_kept, multi_chain


def build_procedures(db: sqlite3.Connection, area: Area):
    """[(airport, kind, designator)] for every airport inside the area."""
    airports = {icao.strip() for icao, lat, lon in db.execute(
        "select airport_identifier, airport_ref_latitude, airport_ref_longitude"
        " from tbl_pa_airports") if icao and area.contains(lat, lon)}

    rows: set[tuple[str, str, str]] = set()
    for kind, table in (("SID", "tbl_pd_sids"), ("STAR", "tbl_pe_stars")):
        for icao, proc in db.execute(
                f"select distinct airport_identifier, procedure_identifier from {table}"):
            if not icao or not proc:
                continue
            icao = icao.strip()
            if icao in airports:
                rows.add((icao, kind, proc.strip()))
    return sorted(rows), len(airports)


def main() -> int:
    here = Path(__file__).resolve().parent.parent
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--db", type=Path, default=here / "db.s3db")
    ap.add_argument("--area", type=Path, default=here / "modes_area.geojson")
    ap.add_argument("--fix-out", type=Path, default=here / "fix.txt")
    ap.add_argument("--airway-out", type=Path, default=here / "airway.txt")
    ap.add_argument("--procedure-out", type=Path, default=here / "procedure.txt")
    args = ap.parse_args()

    area = Area.load(args.area)
    db = sqlite3.connect(f"file:{args.db}?mode=ro", uri=True)
    cycle = (db.execute("select cycle from tbl_hdr_header").fetchone() or ("????",))[0]

    fixes, considered, collisions = build_fixes(db, area)
    airways, outside_kept, split_names = build_airways(db, area)
    procedures, procedure_airports = build_procedures(db, area)

    lines = [FIX_HEADER.format(cycle=cycle)]
    for ident in sorted(fixes):
        lat, lon, _ = fixes[ident]
        lines.append(f"{ident} {lat!r} {lon!r}")
    args.fix_out.write_text("\n".join(lines) + "\n", encoding="utf-8")

    lines = [AIRWAY_HEADER.format(cycle=cycle)]
    for name, idents in airways:
        lines.append(f"AIRWAY {name}")
        lines.extend(idents)
        lines.append("")
    args.airway_out.write_text("\n".join(lines).rstrip("\n") + "\n", encoding="utf-8")

    lines = [PROCEDURE_HEADER.format(cycle=cycle)]
    lines.extend(f"{icao} {kind} {proc}" for icao, kind, proc in procedures)
    args.procedure_out.write_text("\n".join(lines) + "\n", encoding="utf-8")

    by_section: dict[str, int] = defaultdict(int)
    for _, _, section in fixes.values():
        by_section[section] += 1

    print(f"AIRAC {cycle}")
    print(f"fix.txt     {len(fixes):,} fixes inside the area "
          f"(of {considered:,} worldwide)")
    for section, n in sorted(by_section.items()):
        print(f"              {section:<10} {n:,}")
    if collisions:
        print(f"              {collisions:,} duplicate idents inside the area, first kept")
    print(f"airway.txt  {len(airways):,} airways, "
          f"{sum(len(i) for _, i in airways):,} fixes listed")
    print(f"              {outside_kept:,} of those are OUTSIDE the area "
          f"(kept on purpose -- see the file header)")
    if split_names:
        print(f"              {split_names} designators span more than one block")
    sids = sum(1 for _, kind, _ in procedures if kind == "SID")
    print(f"procedure.txt {len(procedures):,} designators at {procedure_airports:,} "
          f"in-area airports")
    print(f"              SID {sids:,}   STAR {len(procedures) - sids:,}")
    for path in (args.fix_out, args.airway_out, args.procedure_out):
        print(f"wrote {path} ({path.stat().st_size / 1024:.0f} KiB)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
